### ISSUE TITLE
In Chinese mode, the display of the text "Simplified Chinese:" will result in an extra line.

### ISSUE THREAD

**Issue by SleepyAsh0191** [xicri/genshin-dictionary#86] opened 2023-03-26 05:11 UTC
![image](https://user-images.githubusercontent.com/64446140/227756449-276ff1ea-3928-4802-98b2-8b5b4f6e95a0.png)

I personally feel that this display effect looks a bit awkward. Shouldn't we switch it to a synonym, such as "简中" (short for "简体中文")?

**Comment by xicri** [comment] 2023-03-26 06:29
@SleepyAsh0191 Thanks for reporting!

I tried to reproduce it on my PC (latest Chrome) and I couldn't reproduce it until I narrowed the screen width to less than 162px. I guess your smartphone's width is larger than 162px.
I couldn't reproduce it on my smartphone (Pixel 6 Pro: resolution width = 1440px, latest Chrome and Firefox) either.

I guess it might depend on the browser.

Can you tell me the following information about your environment?

- OS
- browser name (Also check if it is the latest version)
- resolution (width) or device name

Can you also check if this happens on Chrome (PC or Android) if possible?

> Shouldn't we switch it to a synonym, such as "简中" (short for "简体中文")?

Is "简中" commonly used by (Simplified) Chinese speakers?
If it sounds natural for Chinese speakers, it looks good solution.

**Comment by SleepyAsh0191** [comment] 2023-03-26 07:00
@xicri It's on my pc(Windows 11, Chrome 109.0.5414.120, 1920x1080)
![image](https://user-images.githubusercontent.com/64446140/227760402-8610cecd-91fc-4647-a03c-7064c154f4a1.png)

**Comment by xicri** [comment] 2023-03-26 07:07
@SleepyAsh0191 Oops, Noto Sans CJK **JP** is specified as the font. The browser may be using another font since there is no such font installed on Windows.
I will consider using web fonts so the Noto Sans CJK (not JP) is used in any environment.

**Comment by xicri** [comment] 2023-04-02 23:36
I'm currently working on framework migration from Nuxt 2 to Next.js.
I will fix this bug after the migration.

**Comment by xicri** [comment] 2023-05-30 23:27
The fix has been reverted due to reverting migration to Next.js. (#115)

**Closed** 2023-09-01 11:45 UTC
Labels: bug, priority: high
